%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:MonitorConfig 
sleep: 1
targets: 
  - 
    name: Build frontend
    paths: [.]
    commands:
      - karun app.nim
    extensions: [.nim]
    files: []
    exclude_extensions: []
    exclude_files: []
    once: false
